[package]
name = "mqtt"
version = "0.0.1"
authors = ["Atila Neves <aalvesne@cisco.com>"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
lto = true

[dependencies]
mio = "0.4.1"
